# projectKey e organization definidos dinamicamente no CI
sonar.organization=fga-eps-mds-1

sonar.host.url=https://sonarcloud.io

sonar.sources=src,webview-ui/src
sonar.language=ts

sonar.typescript.tsconfigPath=./tsconfig.json

sonar.tests=src,webview-ui/src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx

sonar.exclusions=**/*.d.ts,out/**,webview-ui/dist/**,node_modules/**,webview-ui/node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info,webview-ui/coverage/lcov.info

sonar.sourceEncoding=UTF-8
